const data={
    besinler:[
     {
     _id:'1',
     name:'Yulaf',
     kalori:360,
     karbonhidrat:49,
     yag:8,
     protein:12,
     tuz:0,
     lif:10,
     saglikdurumu:'iyi',  
     miktar:'100 gr'
    },
   {
     _id:'2',
     name:'Yumurta',
     karbonhidrat:1,
     kalori:120,
     yag:8,
     protein:10,
     tuz:0,
     lif:0,
     saglikdurumu:'iyi', 
    miktar:'100 gr' 
    },
   {
     _id:'3',
     name:'Süt',
     karbonhidrat:10,
     kalori:42,
     yag:1,
     protein:4,
     tuz:2,
     lif:0,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'4',
     name:'Tavuk',
     karbonhidrat:0,
     kalori:239,
     yag:14,
     protein:27,
     tuz:2,
     lif:0,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'5',
     name:'Et',
     karbonhidrat:0,
     kalori:172,
     yag:8,
     protein:24,
     tuz:2,
     lif:0,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'6',
     name:'Balık',
     karbonhidrat:0,
     Kalori:205,
     yag:12,
     protein:22,
     tuz:2,
     lif:0,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'7',
     name:'Elma',
     karbonhidrat:12,
     kalori:52,
     yag:7,
     protein:0,
     tuz:1,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'8',
     name:'Muz',
     karbonhidrat:38,
     kalori:151,
     yag:0,
     protein:2,
     tuz:1,
     lif:5,
     saglikdurumu:'iyi',  
    miktar:'100 gr'
    },
   {
     _id:'9',
     name:'Kivi',
     kalori:42,
     karbonhidrat:10,
     yag:0,
     protein:0,
     tuz:1,
     lif:3,
     saglikdurumu:'iyi',  
    miktar:'100 gr'
    },
   {
     _id:'10',
     name:'Pirinc',
     kalori:130,
     karbonhidrat:28,
     yag:0,
     protein:3,
     tuz:1,
     lif:0,
     saglikdurumu:'orta', 
    miktar:'100 gr' 
    },
   {
     _id:'11',
     name:'Mercimek Çorba Kırmızı',
     kalori:130,
     karbonhidrat:28,
     yag:3,
     protein:3,
     tuz:1,
     lif:2,
     saglikdurumu:'iyi', 
    miktar:'100 gr' 
    },
   {
     _id:'12',
     name:'Dondurma',
     kalori:130,
     karbonhidrat:28,
     yag:7,
     protein:4,
     tuz:1,
     lif:0,
     saglikdurumu:'kötü', 
    miktar:'100 gr' 
    },
   {
     _id:'13',
     name:'Hamburger',
     kalori:530,
     karbonhidrat:68,
     yag:45,
     protein:17,
     tuz:5,
     lif:1,
     saglikdurumu:'kötü', 
    miktar:'100 gr' 
    },
   
   
   {
     _id:'14',
   kalori:300,
     name:'Et Döner',
     karbonhidrat:8,
     yag:27,
     protein:14,
     tuz:3,
     lif:5,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'15',
   kalori:350,
     name:'Makarna',
     karbonhidrat:66,
     yag:5,
     protein:15,
     tuz:2,
     lif:2,
     saglikdurumu:'orta',  
    miktar:'100 gr'
    },
   {
     _id:'16',
     kalori:250,
     name:'Lahmacun',
     karbonhidrat:36,
     yag:10,
     protein:12,
     tuz:2,
     lif:7,
     saglikdurumu:'orta', 
    miktar:'100 gr' 
    },
   {
     _id:'17',
     kalori:350,
     name:'Adana Kebap',
     karbonhidrat:8,
     yag:37,
     protein:22,
     tuz:4,
     lif:0,
     saglikdurumu:'orta',  
    miktar:'100 gr'
    },
   {
     _id:'18',
     kalori:264,
     name:'Ekmek',
     karbonhidrat:49,
     yag:3,
     protein:9,
     tuz:2,
     lif:3,
     saglikdurumu:'iyi', 
    miktar:'100 gr' 
    },
   {
     _id:'19',
     kalori:470,
     name:'Badem',
     karbonhidrat:46,
     yag:37,
     protein:20,
     tuz:3,
     lif:6,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'20',
     kalori:450,
     name:'Fındık',
     karbonhidrat:46,
     yag:47,
     protein:18,
     tuz:2,
     lif:4,
     saglikdurumu:'iyi', 
    miktar:'100 gr' 
    },
   {
     _id:'21',
   kalori:450,
     name:'Fıstık',
     karbonhidrat:46,
     yag:45,
     protein:23,
     tuz:1,
     lif:3,
     saglikdurumu:'iyi', 
    miktar:'100 gr' 
    },
   {
     _id:'22',
     kalori:450,
     name:'Antep Fıstıgı',
     karbonhidrat:45,
     yag:50,
     protein:24,
     tuz:5,
     lif:2,
     saglikdurumu:'orta', 
    miktar:'100 gr' 
    },
   {
     _id:'23',
     kalori:250,
     name:'Çiğ Köfte',
     karbonhidrat:45,
     yag:12,
     protein:9,
     tuz:2,
     lif:3,
     saglikdurumu:'orta',  
    miktar:'100 gr'
    },
   {
     _id:'24',
     kalori:300,
     name:'Çikolata',
     karbonhidrat:30,
     yag:32,
     protein:3,
     tuz:1,
     lif:2,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'25',
     kalori:364,
     name:'Beyaz Un',
     karbonhidrat:76,
     yag:1,
     protein:10,
     tuz:1,
     lif:3,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'26',
     kalori:370,
     name:'Cips',
     karbonhidrat:56,
     yag:32,
     protein:6,
     tuz:5,
     lif:3,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'27',
     kalori:130,
     name:'Zeytin',
     karbonhidrat:6,
     yag:11,
     protein:1,
     tuz:4,
     lif:3,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'28',
     kalori:15,
     name:'Salatalık',
     karbonhidrat:4,
     yag:0,
     protein:1,
     tuz:0,
     lif:1,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'29',
     kalori:41,
     name:'Havuç',
     karbonhidrat:10,
     yag:0,
     protein:1,
     tuz:0,
     lif:3,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'30',
     kalori:120,
     name:'Kinoa',
     karbonhidrat:21,
     yag:2,
     protein:4,
     tuz:0,
     lif:3,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'31',
   kalori:63,
     name:'Kiraz',
     karbonhidrat:16,
     yag:0,
     protein:1,
     tuz:0,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'32',
     kalori:30,
     name:'Karpuz',
     karbonhidrat:8,
     yag:0,
     protein:1,
     tuz:0,
     lif:1,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'33',
     kalori:40,
     name:'Şekerli Kola',
     karbonhidrat:12,
     yag:0,
     protein:0,
     tuz:0,
     lif:10,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'34',
     kalori:40,
     name:'Gazoz',
     karbonhidrat:11,
     yag:0,
     protein:0,
     tuz:1,
     lif:0,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'35',
      kalori:350,
     name:'Kokoreç',
     karbonhidrat:8,
     yag:45,
     protein:12,
     tuz:3,
     lif:1,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'36',
     kalori:46,
     name:'Mercimek Çorba',
     karbonhidrat:8,
     yag:1,
     protein:3,
     tuz:1,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'37',
     kalori:61,
     name:'Pırasa',
     karbonhidrat:14,
     yag:0,
     protein:1,
     tuz:0,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'38',
     kalori:28,
     name:'Limon',
     karbonhidrat:9,
     yag:0,
     protein:1,
     tuz:2,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'39',
      kalori:150,
     name:'İşkembe Çorba',
     karbonhidrat:4,
     yag:7,
     protein:15,
     tuz:4,
     lif:0,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'40',
     kalori:94,
     name:'Şehriye Corba',
     karbonhidrat:24,
     yag:4,
     protein:5,
     tuz:2,
     lif:3,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'41',
     kalori:278,
     name:'Reçel',
     karbonhidrat:69,
     yag:1,
     protein:0,
     tuz:1,
     lif:1,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'42',
     kalori:203,
     name:'Tavuk Kanat',
     karbonhidrat:0,
     yag:12,
     protein:17,
     tuz:2,
     lif:0,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'43',
     kalori:177,
     name:'Tavuk Pirzola',
     karbonhidrat:0,
     yag:12,
     protein:18,
     tuz:2,
     lif:0,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'44',
     kalori:884,
     name:'Zeytinyağı',
     karbonhidrat:0,
     yag:100,
     protein:0,
     tuz:1,
     lif:0,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'45',
     kalori:884,
     name:'Ayçiçek Yağı',
     karbonhidrat:0,
     yag:100,
     protein:0,
     tuz:0,
     lif:0,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'46',
      kalori:331,
     name:'Sucuk',
     karbonhidrat:5,
     yag:28,
     protein:14,
     tuz:6,
     lif:0,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'47',
      kalori:342,
     name:'Bulgur',
     karbonhidrat:76,
     yag:2,
     protein:12,
     tuz:3,
     lif:18,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'48',
     kalori:311,
     name:'Patates Kızartması',
     karbonhidrat:41,
     yag:15,
     protein:3,
     tuz:6,
     lif:4,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'49',
     kalori:77,
     name:'Patates',
     karbonhidrat:18,
     yag:0,
     protein:2,
     tuz:3,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'50',
     kalori:111,
     name:'Ketçap',
     karbonhidrat:26,
     yag:0,
     protein:1,
     tuz:2,
     lif:0,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'51',
     kalori:679,
     name:'Mayonez',
     karbonhidrat:0,
     yag:75,
     protein:1,
     tuz:10,
     lif:0,
     saglikdurumu:'kötü',
    miktar:'100 gr'  
    },
   {
     _id:'52',
     kalori:365,
     name:'Sarı Mısır',
     karbonhidrat:74,
     yag:5,
     protein:10,
     tuz:3,
     lif:8,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    },
   {
     _id:'53',
      kalori:374,
     name:'Patlamış Mısır',
     karbonhidrat:74,
     yag:5,
     protein:11,
     tuz:3,
     lif:13,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'54',
      kalori:716,
     name:'Tereyağı',
     karbonhidrat:0,
     yag:81,
     protein:1,
     tuz:1,
     lif:0,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'55',
      kalori:290,
     name:'Pekmez',
     karbonhidrat:74,
     yag:0,
     protein:0,
     tuz:0,
     lif:0,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'56',
     kalori:304,
     name:'Bal',
     karbonhidrat:82,
     yag:0,
     protein:0,
     tuz:2,
     lif:0,
     saglikdurumu:'orta',
    miktar:'100 gr'  
    },
   {
     _id:'57',
     kalori:47,
     name:'Portakal',
     karbonhidrat:12,
     yag:0,
     protein:1,
     tuz:0,
     lif:2,
     saglikdurumu:'iyi',
    miktar:'100 gr'  
    } ] }

    export default data